- name: Install nginx 
  hosts: web 
  tasks: 
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx 
      state: installed 
    when: anible_os_family == "Redhat"

  - name: install nginx when os family is ubuntu 
    ansible.builtin.apt:
      name: nginx 
      state: installed 
    when: ansible_os_family == "Debian"  