- name: Install nginx
  hosts: web
  gather_facts: yes
  tasks:
    - name: Install nginx on RedHat family
      ansible.builtin.dnf:
        name: nginx
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install nginx on Debian family
      ansible.builtin.apt:
        name: nginx
        state: installed
      when: ansible_os_family == "Debian"
