- name: undefined vasibels 
  hosts: local 
  connection: local 
  tasks: 
  - name: handle undefined variables 
    ansible.builtin.debug: 
      msg: "Hello {{ person | default('trinath') }}"

  - name: converting string to list 
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug: 
      msg: "{{ fruits | split (',') }}"

      