  - name: create ec2 instances and route53 domains 
    hosts: local 
    connection: local
    vars:
      subnet_id: subnet-0f970ac6fb262b6cb
      sg_id: sg-0e142280b2978f20a
      ami_id: ami-09c813fb71547fc4f
      instance_type: t2.micro 
      instances: 
       - mysql 
       - backend 
       - frontend 
    tasks: 
    - name: install Aws Python libraries 
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9 
      loop:
      - boto3 
      - botocore 

    - name: create ec2 instances 
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
